version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports: [ "8080:8080" ]
    environment:
      - CELLS_LOG_LEVEL=production
      - CELLS_BIND=:8080
      - CELLS_EXTERNAL=https://drive.ovcloud.io
      - CELLS_NO_TLS=1
    volumes:
      - data:/var/cells/data
      - cellsdir:/var/cells
    networks:
      - web
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    ports: [ "3306:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cells
      MYSQL_USER: cells
      MYSQL_PASSWORD: password
    volumes:
      - mysqldir:/var/lib/mysql
    networks:
      - web

  collabora:
    image: collabora/code
    restart: unless-stopped
    ports: [ "9980:9980" ]
    environment:
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - "username=admin"
      - "password=admin"
      - "domain=172\\.16\\.0\\.15"
      - "server_name=172.16.0.15"
    cap_add:
      - MKNOD
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: [ "8081:8080" ]
    environment:
      - PMA_ARBITRARY=1
    networks:
      - web
    depends_on:
      - db

volumes:
  data: {}
  cellsdir: {}
  mysqldir: {}
