version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports: [ "8080:8080" ]
    environment:
      - CELLS_LOG_LEVEL=production
      - CELLS_BIND=:8080
    volumes:
      - data:/var/cells/data
      - cellsdir:/var/cells
    labels:
      - traefik.http.routers.blog.rule=Host(`drive.ovcloud.io`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD:
    networks:
      - internal
    labels:
      - traefik.enable=false

volumes:
  data: {}
  cellsdir: {}
  mysqldir: {}
