[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$Ix5iqUKo$My9i4AU9bv0QnyVCNc/1f0"
  ]

[http.routers.api]
  rule = "Host(`monitor.ovcloud.io`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
